// app
export const START_LOADING = 'START_LOADING';
export const STOP_LOADING = 'STOP_LOADING';
export const INITIALIZE = 'INITIALIZE';
export const CONFIUGRE = 'CONFIUGRE';
export const TOGGLE_SIDEBAR = 'TOGGLE_SIDEBAR';
export const SET_SELECTED = 'SET_SELECTED';

// movies
export const FETCH_MOVIES_START = 'FETCH_MOVIE_START';
export const FETCH_MOVIES_FINISH = 'FETCH_MOVIE_FINISH';
export const CHANGE_MOVIES_PAGE = 'CHANGE_MOVIE_PAGE';
export const FETCH_MOVIES = 'FETCH_MOVIES';
export const FETCH_MOVIE_GENRES = 'FETCH_MOVIE_GENRES';

//singleIMovie
export const FETCH_SINGLEMOVIE_START = 'FETCH_SINGLEMOVIE_START';
export const FETCH_SINGLEMOVIE_FINISH = 'FETCH_SINGLEMOVIE_FINISH';
export const FETCH_SINGLEMOVIE = 'FETCH_SINGLEMOVIE';

//movieRecom
export const FETCH_MOVIERECOM_START = 'FETCH_MOVIERECOM_START';
export const FETCH_MOVIERECOM_FINISH = 'FETCH_MOVIERECOM_FINISH';
export const FETCH_MOVIERECOM = 'FETCH_MOVIERECOM';
export const CHANGE_MOVIERECOM_PAGE = 'CHANGE_MOVIERECOM_PAGE';

//discoverMovies
export const DISCOVER_MOVIES_START = 'DISCOVER_MOVIES_START';
export const DISCOVER_MOVIES_FINISH = 'DISCOVER_MOVIES_FINISH';
export const DISCOVER_MOVIES = 'DISCOVER_MOVIES';
export const CHANGE_DISCOVER_MOVIES_PAGE = 'CHANGE_DISCOVER_MOVIES_PAGE';

//peoples
export const FETCH_PERSON_START = 'FETCH_PERSON_START';
export const FETCH_PERSON_FINISH = 'FETCH_PERSON_FINISH';
export const FETCH_PERSON = 'FETCH_PERSON';
export const FETCH_MOVIE_WITH_PERSON = 'FETCH_MOVIE_WITH_PERSON';

export const FETCH_TVSHOWS = 'FETCH_TVSHOWS';
export const FETCH_TVSHOW_GENRES = 'FETCH_TVSHOW_GENRES';

export const REQUEST_FAILED = 'REQUEST_FAILED';
export const REQUEST_SUCCEEDED = 'REQUEST_SUCCEEDED';
