// app
export const START_LOADING = 'START_LOADING';
export const STOP_LOADING = 'STOP_LOADING';
export const INITIALIZE = 'INITIALIZE';
export const CONFIUGRE = 'CONFIUGRE';
export const TOGGLE_SIDEBAR = 'TOGGLE_SIDEBAR';
export const SET_SELECTED = 'SET_SELECTED';

// movies
export const FETCH_MOVIES_START = 'FETCH_MOVIE_START';
export const FETCH_MOVIES_FINISH = 'FETCH_MOVIE_FINISH';
export const CHANGE_MOVIES_PAGE = 'CHANGE_MOVIE_PAGE';
export const FETCH_MOVIES = 'FETCH_MOVIES';
export const FETCH_MOVIE_GENRES = 'FETCH_MOVIE_GENRES';

//singleIMovie
export const FETCH_SINGLEMOVIE_START = 'FETCH_SINGLEMOVIE_START';
export const FETCH_SINGLEMOVIE_FINISH = 'FETCH_SINGLEMOVIE_FINISH';
export const FETCH_SINGLEMOVIE = 'FETCH_SINGLEMOVIE';

export const FETCH_TVSHOWS = 'FETCH_TVSHOWS';
export const FETCH_TVSHOW_GENRES = 'FETCH_TVSHOW_GENRES';

export const REQUEST_FAILED = 'REQUEST_FAILED';
export const REQUEST_SUCCEEDED = 'REQUEST_SUCCEEDED';
